"""
Markdown报告格式化器

将扫描结果格式化为Markdown格式的报告。
"""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..scanner import ScanResult

from .base import BaseFormatter


class MarkdownFormatter(BaseFormatter):
    """Markdown格式化器"""

    def format(self, result: "ScanResult") -> str:
        """格式化为Markdown报告

        Args:
            result: 扫描结果

        Returns:
            Markdown字符串
        """
        lines: list = []

        lines.append("# PyGuard-CLI 代码质量报告")
        lines.append("")

        # 摘要表格
        lines.append("## 摘要")
        lines.append("")
        lines.append("| 指标 | 数值 |")
        lines.append("|------|------|")
        lines.append(f"| 扫描文件数 | {result.files_scanned} |")
        lines.append(f"| 问题文件数 | {result.files_with_issues} |")
        lines.append(f"| 代码总行数 | {result.total_lines} |")
        lines.append(f"| 扫描耗时 | {result.scan_time:.3f}s |")
        lines.append(f"| **错误** | **{result.error_count}** |")
        lines.append(f"| **警告** | **{result.warning_count}** |")
        lines.append(f"| **信息** | **{result.info_count}** |")
        lines.append(f"| **总计** | **{len(result.issues)}** |")
        lines.append("")

        # 分类统计
        category_counts: dict = {}
        for issue in result.issues:
            cat = issue.category
            category_counts[cat] = category_counts.get(cat, 0) + 1

        if category_counts:
            category_names = {
                "type": "类型检查",
                "style": "代码风格",
                "security": "安全检测",
                "complexity": "复杂度分析",
                "performance": "性能建议",
                "best_practice": "最佳实践",
                "scanner": "扫描错误",
            }
            lines.append("## 问题分类")
            lines.append("")
            lines.append("| 分类 | 数量 |")
            lines.append("|------|------|")
            for cat, count in sorted(category_counts.items()):
                name = category_names.get(cat, cat)
                lines.append(f"| {name} | {count} |")
            lines.append("")

        # 问题详情
        if result.issues:
            lines.append("## 问题详情")
            lines.append("")

            severity_icons = {"error": "X", "warning": "!", "info": "i"}
            current_file = ""

            for issue in result.issues:
                if issue.file_path != current_file:
                    current_file = issue.file_path
                    lines.append(f"### `{current_file}`")
                    lines.append("")

                icon = severity_icons.get(issue.severity, "?")
                lines.append(
                    f"- **[{icon}] {issue.rule_id}** "
                    f"(L{issue.line_no}:C{issue.column}) "
                    f"{issue.message}"
                )
                if issue.suggestion:
                    lines.append(f"  - 建议: {issue.suggestion}")
            lines.append("")
        else:
            lines.append("## 结果")
            lines.append("")
            lines.append("未发现问题，代码质量良好!")
            lines.append("")

        lines.append("---")
        lines.append("*Generated by PyGuard-CLI v1.0.0*")

        return "\n".join(lines)
